name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ukamed
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ukamed/my-node-app:${{ env.TAG }}

    - name: Set Docker Image tag
      env:
        TAG: ${{ env.TAG }}
      run: |
        echo "::set-env name=TAG::$(date +%s)"
