name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ukamed
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

#     - name: Set short git commit SHA
#       id: vars
#       run: |
#         ls -la
#         calculatedSha=$(git rev-parse --short ${{ github.sha }})
#         echo "::set-output name=short_sha::$calculatedSha"
        
#     - name: Confirm git commit SHA output
#       run: echo ${{ steps.vars.outputs.short_sha }}

    - name: Set Docker Image tag
      env:
        TAG: ${{ env.TAG }}
      run: |
        echo "::set-env name=TAG::$(date +%s)"
    
    
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ukamed/my-node-app:${{ env.TAG }}
